/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","zh",{euro:"欧元符号",lsquo:"左单引号",rsquo:"右单引号",ldquo:"左双引号",rdquo:"右双引号",ndash:"短破折号",mdash:"长破折号",iexcl:"倒置的惊叹号",cent:"美分符号",pound:"英镑符号",curren:"货币符号",yen:"日元符号",brvbar:"竖线",sect:"章节符号",uml:"分音符号",copy:"版权符号",ordf:"雌性符号",laquo:"左双角括号",not:"Not 符号",reg:"注册商标符号",macr:"长音符号",deg:"度数符号",sup2:"上标字 2",sup3:"上标字 3",acute:"尖音符号",micro:"微标志",para:"段落符号",middot:"中间点",cedil:"字母 C 下面的尾型符号 ",sup1:"上标",ordm:"雄性符号",raquo:"右双角括号",frac14:"四分之一符号",frac12:"普通分数一半",
frac34:"普通分数三分之一",iquest:"倒置的问号",Agrave:"带严肃口音的拉丁文大写字母",Aacute:"大写字母拉丁字母",Acirc:"带字母的拉丁文大写字母A",Atilde:"拉丁文大写字母",Auml:"拉丁大写字母 E 带分音符号",Aring:"拉丁大写字母 A 带上圆圈",AElig:"拉丁大写字母 Æ",Ccedil:"拉丁大写字母 C 带下尾符号",Egrave:"带严肃口音的拉丁文大写字母E",Eacute:"拉丁字母大写字母E",Ecirc:"带字母的拉丁大写字母E",Euml:"拉丁文大写字母E分音符",
Igrave:"拉丁文大写字母我带着严肃的口音",Iacute:"带着尖锐的口音的拉丁文大写字母I",Icirc:"大写字母拉丁字母",Iuml:"拉丁文大写字母分音符I",ETH:"拉丁文大写字母e",Ntilde:"拉丁文大写字母N",Ograve:"带着严肃的口音的拉丁文大写字母o",Oacute:"大写字母拉丁字母o",Ocirc:"带字母的拉丁文大写字母O",Otilde:"拉丁文大写字母O",Ouml:"拉丁文大写字母O分音符",
times:"乘号",Oslash:"拉丁大写字母 O 带粗线符号",Ugrave:"带严肃口音的拉丁文大写字母u",Uacute:"带急性口音的拉丁文大写字母u",Ucirc:"带字母的拉丁大写字母u",Uuml:"Latin capital letter U with diaeresis",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Latin small letter sharp s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",
auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"Latin small letter æ",ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",
eth:"Latin small letter eth",ntilde:"Latin small letter n with tilde",ograve:"Latin small letter o with grave accent",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"Division sign",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",
uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"Latin small letter thorn",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",
hellip:"Horizontal ellipsis",trade:"Trade mark sign",9658:"Black right-pointing pointer",bull:"Bullet",rarr:"Rightwards arrow",rArr:"向右双箭头",hArr:"Left right double arrow",diams:"Black diamond suit",asymp:"Almost equal to"});